onCull = true
MaxEntityEntities = 1024
EntitiesDistance = 512
qualityModes = "ultra"
RenderWeather = "normal"
RenderTNTExplosions = true
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
startTime = 50.306
chatFix = false
onGui = false
GuiRXTX = false
GuiFPS = false
GuiCPU = false
GuiGPU = false
GuiRAM = false
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = false
GuiCameraTarget = false
Mood = false
Particle = true
BlockBreakParticleMode = "ultra"
MaxParticleDistance = 512
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = true
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
EntityRender = true
UseVanillaGui = false
DeBug = false
TextBackground = false
